basePath: /api/v1
definitions:
  common.ApiError:
    properties:
      code:
        type: integer
      message:
        type: string
      statusCode:
        type: integer
    type: object
  request.InMemoryCreateRecordRequest:
    properties:
      key:
        type: string
      value:
        type: string
    required:
    - key
    - value
    type: object
  request.MongoGetRecordsRequest:
    properties:
      endDate:
        example: "2021-01-02"
        type: string
      maxCount:
        example: 3000
        type: integer
      minCount:
        example: 2800
        type: integer
      startDate:
        example: "2016-10-02"
        type: string
    required:
    - endDate
    - maxCount
    - minCount
    - startDate
    type: object
  response.InMemoryRecordResponse:
    properties:
      key:
        type: string
      value:
        type: string
    type: object
  response.MongoRecordResponse:
    properties:
      createdAt:
        type: string
      key:
        type: string
      totalCount:
        type: integer
    type: object
  response.MongoRecordsResponse:
    properties:
      code:
        type: integer
      msg:
        type: string
      records:
        items:
          $ref: '#/definitions/response.MongoRecordResponse'
        type: array
    type: object
host: go-pure-api.herokuapp.com
info:
  contact: {}
  description: A REST API that allows you to get records from mongo database and read/write
    them to in-memory database!
  title: Go Pure API
  version: "1.0"
paths:
  /in-memory:
    get:
      consumes:
      - application/json
      description: This endpoints returns value of the key provided
      parameters:
      - description: Key
        in: query
        name: key
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.InMemoryRecordResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ApiError'
      summary: Gets a value of the key provided
      tags:
      - values
    post:
      consumes:
      - application/json
      description: This endpoints persists a new key-value in the in-memory database
      parameters:
      - description: The key and value that will be persist.
        in: body
        name: Value
        required: true
        schema:
          $ref: '#/definitions/request.InMemoryCreateRecordRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.InMemoryRecordResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ApiError'
      summary: Creates a a new key-value
      tags:
      - values
  /mongo:
    post:
      consumes:
      - application/json
      description: This endpoints returns records from the mongo database with the
        provided filter in request
      parameters:
      - description: Filter for the request
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/request.MongoGetRecordsRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.MongoRecordsResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/common.ApiError'
      summary: Gets a records from database
      tags:
      - values
schemes:
- https
swagger: "2.0"
