// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	server "github.com/yunussandikci/go-pure-api/app/server"
)

// MongoController is an autogenerated mock type for the MongoController type
type MongoController struct {
	mock.Mock
}

// GetRecords provides a mock function with given fields: request, response
func (_m *MongoController) GetRecords(request *server.Request, response *server.Response) {
	_m.Called(request, response)
}
