// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// TestContainer is an autogenerated mock type for the TestContainer type
type TestContainer struct {
	mock.Mock
}

// GetHostPort provides a mock function with given fields: port
func (_m *TestContainer) GetHostPort(port string) string {
	ret := _m.Called(port)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(port)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Terminate provides a mock function with given fields:
func (_m *TestContainer) Terminate() {
	_m.Called()
}
